---
title: "Exp2_fill_manon"
output: html_document
---

```{r results='hide', message=FALSE, warning=FALSE}
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE)
library(tidyverse)
library(reshape2)
library(lme4)
library(corrplot)
library(jtools)
library(dotwhisker)
library(broom)
library(knitr)
library(ggfortify)
library(nlme)
library(simr)
library(pscl)
library(foreign)
library("gdata")
library('ri2')
library(eeptools)
#library(lmerTest)
```

```{r results='hide', message=FALSE, warning=FALSE}
### Reading and cleaning data
crn_experiment_data2 <- read_csv("/Users/Manon/Desktop/Current/Projects/behavioral_exp/data/Experiment2_February2020.csv") %>% filter(Q1 == "I agree to participate", Finished == "True") 
nrow(crn_experiment_data2)
```

```{r}
treatment <- crn_experiment_data2 %>% select(paste("image", 0:5, sep = "")) %>% 
  rowid_to_column("ID") %>% 
  gather(key = "image", value = "stimuli", ... = -ID) %>% arrange(ID) %>%
  separate(col = stimuli, into = c('NA1', 'NA2', 'NA3', 'NA4', "Publisher", "Article", "CRN", 'NA5'), sep = "_|/") %>% 
  separate(col = CRN, into = c("CRN", 'NA6')) %>% select(-image)

trustworthy <- crn_experiment_data2 %>% select(Q722_1, Q729_1, Q730_1, Q731_1, Q732_1, Q733_1) %>% 
  rowid_to_column("ID") %>% 
  gather(key = "question", value = "trust", ... = -ID) %>% arrange(ID) %>% select(trust) %>%
  mutate(trust = unclass(factor(trust, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree",
                                                 "Somewhat agree", "Strongly agree"))))

false <- crn_experiment_data2 %>% select(Q722_2, Q729_2, Q730_2, Q731_2, Q732_2, Q733_2) %>%  
  rowid_to_column("ID") %>% 
  gather(key = "question", value = "false", ... = -ID) %>% arrange(ID) %>% select(false) %>%
  mutate(false = unclass(factor(false, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree",
                                                 "Somewhat agree", "Strongly agree"))))

biased <- crn_experiment_data2 %>% select(Q722_3, Q729_3, Q730_3, Q731_3, Q732_3, Q733_3) %>%  
  rowid_to_column("ID") %>% 
  gather(key = "question", value = "biased", ... = -ID) %>% arrange(ID) %>% select(biased) %>%
  mutate(biased = unclass(factor(biased, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree",
                                                 "Somewhat agree", "Strongly agree"))))

credible <- crn_experiment_data2 %>% select(Q722_4, Q729_4, Q730_4, Q731_4, Q732_4, Q733_4) %>%  
  rowid_to_column("ID") %>% 
  gather(key = "question", value = "credible", ... = -ID) %>% arrange(ID) %>% select(credible) %>%
  mutate(credible = unclass(factor(credible, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree",
                                                 "Somewhat agree", "Strongly agree"))))

informative <- crn_experiment_data2 %>% select(Q722_5, Q729_5, Q730_5, Q731_5, Q732_5, Q733_5) %>%  
  rowid_to_column("ID") %>% 
  gather(key = "question", value = "informative", ... = -ID) %>% arrange(ID) %>% select(informative) %>%
  mutate(informative = unclass(factor(informative, levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree",
                                                 "Somewhat agree", "Strongly agree"))))

output_estimate <- cbind(treatment, trustworthy, false, biased, credible, informative) 

output_estimate$false_inverse <- 5 - output_estimate$false
output_estimate$biased_inverse <- 5 - output_estimate$biased
output_estimate$mean_estimate <- rowMeans(subset(output_estimate, select = c(trust, informative, credible, false_inverse, biased_inverse)), na.rm = TRUE)

output_estimate$mean_estimate_positive <- rowMeans(subset(output_estimate, select = c(trust, informative, credible)), na.rm = TRUE)

output_estimate$mean_estimate_negative <- rowMeans(subset(output_estimate, select = c(false_inverse, biased_inverse)), na.rm = TRUE)
output_estimate[, "max_estimate"] <- apply(output_estimate[,c("trust", "informative", "credible", "false_inverse", "biased_inverse")], 1, max, na.rm = TRUE)

familiarity <- crn_experiment_data2 %>% select(Q845_12:Q845_19) %>% 
  rename(fox = Q845_12, atlantic = Q845_13, cnn = Q845_14, sacbee = Q845_15, 
         vox = Q845_16, daytonabeach = Q845_17, denverpost = Q845_18, usatoday = Q845_19) %>% 
  mutate_at(funs(factor), .vars = 1:8) %>% rowid_to_column("ID") %>% 
  inner_join(treatment, by = "ID") %>% select(-Article, -CRN) %>% 
  gather(key = "Source", value = "familiarity", ... = -c(Publisher,ID)) %>%
  filter(Publisher == Source) %>% arrange(ID) %>% select(ID, Publisher, familiarity)


# media_balance <- crn_experiment_data2 %>% select(Q384_12:Q384_19) %>% 
#   rename(fox = Q384_12, atlantic = Q384_13, cnn = Q384_14, sacbee = Q384_15, 
#          vox = Q384_16, daytonabeach = Q384_17, denverpost = Q384_18, usatoday = Q384_19) %>% 
#   mutate_at(funs(factor), .vars = 1:8) %>% rowid_to_column("ID") %>% 
#   inner_join(treatment, by = "ID") %>% select(-Article, -CRN) %>% 
#   gather(key = "Source", value = "media_balance", ... = -c(Publisher,ID)) %>%
#   filter(Publisher == Source) %>% arrange(ID) %>% select(ID, Publisher, media_balance)

output_estimate <- inner_join(output_estimate, familiarity)

features <- crn_experiment_data2 %>% select(Q735, Q737, Q32) %>%
  rename(ad_notice = Q735, ad_blocker = Q737, pol_leaning = Q32) %>% rowid_to_column("ID")

screeners <- crn_experiment_data2 %>% rowid_to_column(var = "ID") %>% 
  select(ID, Q773, Q797, Q1_1, Q1_6) %>% 
  rename(scr_color = Q773, scr_web = Q797, scr_grid_ww2 = Q1_1, scr_grid_middle = Q1_6) %>%
  mutate(scr_color = as.numeric(scr_color == "Red,Green"), 
         scr_web = as.numeric(scr_web == "The Drudge Report,ABC News website"), 
         scr_grid_ww2 = as.numeric(scr_grid_ww2 == "Disagree\nstrongly" | scr_grid_ww2 == "Disagree"),
         scr_grid_middle = as.numeric(scr_grid_middle == "Neither agree nor disagree")) %>% 
  mutate(attention = scr_color + scr_web + scr_grid_ww2 + scr_grid_middle)

output_estimate <- inner_join(output_estimate, inner_join(features, screeners))

pol_interest <- crn_experiment_data2 %>% select(Q42) %>% rename (pol_interest=Q42) %>% rowid_to_column("ID")
pol_interest$pol_interest[pol_interest$pol_interest == "Hardly at all"] <- 1
pol_interest$pol_interest[pol_interest$pol_interest == "Only now and then"] <- 2
pol_interest$pol_interest[pol_interest$pol_interest == "Some of the time"] <- 3
pol_interest$pol_interest[pol_interest$pol_interest == "Most of the time"] <- 4
output_estimate <- inner_join(output_estimate, inner_join(pol_interest, features))

age <- crn_experiment_data2 %>% select(Q3) %>% rename (age=Q3) %>% rowid_to_column("ID")
age$age <- as.Date(age$age, format = "%Y")
age$age[is.na(age$age)] <- Sys.Date()
age$age <- floor(age_calc(age$age, units = "years"))
age$bin_age <- cut(age$age, seq(0, 90, 10))
output_estimate <- inner_join(output_estimate, inner_join(age, features))

gender <- crn_experiment_data2 %>% select(Q2) %>% rename (gender=Q2) %>% rowid_to_column("ID")
output_estimate <- inner_join(output_estimate, inner_join(gender, features))

education <- crn_experiment_data2 %>% select(Q14) %>% rename (education=Q14) %>% rowid_to_column("ID")
education$education_level <- education$education
education$education_level[education$education_level == "Did not graduate from high school"] <- 1
education$education_level[education$education_level == "High school graduate"] <- 2
education$education_level[education$education_level == "Some college, but no degree"] <- 3
education$education_level[education$education_level == "2-year college degree"] <- 4
education$education_level[education$education_level == "4-year college degree"] <- 5
education$education_level[education$education_level == "Postgraduate degree (MA, MBA, JD, PhD, etc.)"] <- 6
output_estimate <- inner_join(output_estimate, inner_join(education, features))

nct <- crn_experiment_data2 %>% rowid_to_column(var = "ID") %>% 
  select(ID, Q738, Q740) %>% 
  rename(nct_1 = Q738, nct_2 = Q740) %>%
  mutate(nct_1 = as.numeric(nct_1 == "Like it"), 
         nct_2 = as.numeric(nct_2 == "Complex")) %>% 
  mutate(nfc_score = nct_1 + nct_2)

output_estimate <- inner_join(output_estimate, inner_join(features, nct))

output_estimate <- output_estimate %>% mutate(fam_rate = ifelse(Publisher %in% c("cnn", "fox", "usatoday"), "High", 
                                ifelse(Publisher %in% c("atlantic", "denverpost", "vox"), "Medium", "Low"))) %>%
  
  mutate(pol_rate = ifelse(Publisher %in% c("cnn", "atlantic", "vox"), "Liberal", ifelse(Publisher %in% c("fox"), "Conservative", "Neutral/Local"))) %>%
  
  mutate(CRN_quality_general = ifelse(CRN %in% c("lq", "lqpol"), "Lq", 
                              ifelse(CRN %in% c("hq", "hqpol"), "Hq", "NA"))) %>%
  mutate(CRN_quality_Pol = if_else(CRN %in% c("hqpol"), "Hq",
                if_else(CRN %in% c("lqpol"), "Lq",
                if_else(CRN %in% c("na"), "nap", if_else(CRN %in% c("hq", "lq"), "nose", "NA") ))))  %>%
  mutate(CRN_quality_NonPol = ifelse(CRN %in% c("lq"), "Lq", 
                              ifelse(CRN %in% c("hq"), "Hq", 
                              if_else(CRN %in% c("na"), "nap", if_else(CRN %in% c("hqpol", "lqpol"), "nose", "NA"))))) %>%
  mutate(CRN_type = ifelse(CRN %in% c("lqpol", "hqpol"), "Pol", 
                              ifelse(CRN %in% c("lq", "hq"), "NonPol", "NA"))) %>%
  mutate_at(.funs = factor, .vars = c("CRN_type", "CRN_quality_general", "CRN_quality_Pol", "CRN_quality_NonPol", "fam_rate", "pol_rate", "Publisher", "Article", "CRN",  "familiarity", "ad_notice", "ad_blocker", "pol_leaning")) %>%
  
  mutate(CRN_vs_NA = 1/3*as.numeric(CRN_quality_general == "Lq") + 1/3*as.numeric(CRN_quality_general == "Hq") -
           2/3 * as.numeric(CRN_quality_general == "NA"),
         Hq_vs_Lq = 1/2*as.numeric(CRN_quality_general == "Lq") - 1/2*as.numeric(CRN_quality_general == "Hq"),
           Hq_vs_NA = 1/2*as.numeric(CRN_quality_general == "NA") - 1/2*as.numeric(CRN_quality_general == "Hq"),
  Lq_vs_NA = 1/2*as.numeric(CRN_quality_general == "Lq") - 1/2*as.numeric(CRN_quality_general == "NA")) %>%

  
  mutate(CRN_vs_NA_pol = 1/3*as.numeric(CRN_quality_Pol == "Lq") + 1/3*as.numeric(CRN_quality_Pol == "Hq") -
           2/3 * as.numeric(CRN_quality_Pol == "nap"),
         Hq_vs_Lq_pol = 1/2*as.numeric(CRN_quality_Pol == "Hq") - 1/2*as.numeric(CRN_quality_Pol == "Lq")) %>%
  
  mutate(CRN_vs_NA_nonpol = 1/3*as.numeric(CRN_quality_NonPol == "Lq") + 1/3*as.numeric(CRN_quality_NonPol == "Hq") -
           2/3 * as.numeric(CRN_quality_NonPol == "nap"),
         Hq_vs_Lq_nonpol = 1/2*as.numeric(CRN_quality_NonPol == "Hq") - 1/2*as.numeric(CRN_quality_NonPol == "Lq")) %>%
  
mutate(Pol_vs_NonPol = 1/2*as.numeric(CRN_type == "Pol") - 1/2*as.numeric(CRN_type == "NonPol"))

output_estimate$CRN_quality_general <- factor(output_estimate$CRN_quality_general, levels(output_estimate$CRN_quality_general)[c(3,2,1)])
output_estimate$CRN_quality_Pol <- factor(output_estimate$CRN_quality_Pol, levels(output_estimate$CRN_quality_Pol)[c(3,2,1)])
output_estimate$CRN_quality_NonPol <- factor(output_estimate$CRN_quality_NonPol, levels(output_estimate$CRN_quality_NonPol)[c(3,2,1)])
output_estimate$CRN_type <- factor(output_estimate$CRN_type, levels(output_estimate$CRN_type)[c(3,2,1)])

#output_estimate$CRN_quality_Pol[is.na(output_estimate$CRN_quality_Pol)] <- "nap"
#output_estimate$CRN_quality_NonPol[is.na(output_estimate$CRN_quality_NonPol)] <- "nap"

#output_keep <- output_estimate
#output_estimate <- output_keep
 
## Fill NaNs
output_estimate$trust <- ifelse(is.na(output_estimate$trust), output_estimate$mean_estimate, output_estimate$trust)
output_estimate$credible <- ifelse(is.na(output_estimate$credible), output_estimate$mean_estimate, output_estimate$credible)
output_estimate$informative <- ifelse(is.na(output_estimate$informative), output_estimate$mean_estimate, output_estimate$informative)
output_estimate$false <- 5 - ifelse(is.na(output_estimate$false), output_estimate$mean_estimate, output_estimate$false)
output_estimate$biased <- 5 - ifelse(is.na(output_estimate$biased), output_estimate$mean_estimate, output_estimate$biased)

## Remove the people who have NaNs mean estimate (who replied to 0 questions for one article), there are 13 such persons 
new_df <- output_estimate[!is.na(output_estimate$mean_estimate),]
output_estimate <- new_df[new_df$ID %in% names(which(table(new_df$ID) > 5)), ]

#output_estimate3 <- na.omit(Data)
#outpdataoutput_estimate <- output_estimate3[output_estimate3$ID %in% names(which(table(output_estimate3$ID) > 5)), ]
#output_estimate <- na.omit(output_estimate)

## Now, lets create the the column that gives the attentiveness score 
tab <- output_estimate$scr_color+ output_estimate$scr_web + output_estimate$scr_grid_ww2 + output_estimate$scr_grid_middle
output_estimate$col_screener_sum <- tab

output_pca <- prcomp(select(output_estimate, trust:informative), 
                     center = TRUE, scale. = TRUE)
summary(output_pca)
autoplot(output_pca, data = output_estimate, colour = "CRN", loadings = TRUE,
         loadings.label = TRUE)
output_estimate <- output_estimate %>% mutate(PC1 = output_pca$x[,1], PC2 = output_pca$x[,2])

pca_sigma <- as.data.frame(t(apply(output_estimate %>% filter(CRN == "na") %>%
              select(PC1, PC2), 2, sd)))

output_estimate <- output_estimate %>% mutate(avg =1/5*(trust+(5-false_inverse)+(5-biased_inverse)+credible+informative))
avg_sigma <- sd((output_estimate %>% filter(CRN == "na"))$mean_estimate)
```
## Combined measure for 5,026 people (NaNs omits in computing average)
```{r}
lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_leaning + familiarity + CRN_vs_NA) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Hq_vs_Lq) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Pol_vs_NonPol) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + CRN_vs_NA:fam_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + CRN_vs_NA_pol:fam_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + Hq_vs_Lq:fam_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate +  fam_rate:Pol_vs_NonPol) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + familiarity + familiarity:fam_rate + Hq_vs_Lq:fam_rate:familiarity) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + familiarity + familiarity:fam_rate + CRN_vs_NA_pol:fam_rate:familiarity) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")
```

## Combined positive measures (... same as above)
```{r}
lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + CRN_vs_NA) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Hq_vs_Lq) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Pol_vs_NonPol) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + CRN_vs_NA:fam_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + CRN_vs_NA_pol:fam_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + Hq_vs_Lq:fam_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate +  fam_rate:Pol_vs_NonPol) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + familiarity + familiarity:fam_rate + Hq_vs_Lq:fam_rate:familiarity) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + familiarity + familiarity:fam_rate + CRN_vs_NA_pol:fam_rate:familiarity) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + familiarity + familiarity:fam_rate + Hq_vs_NA:fam_rate:familiarity) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_positive/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + familiarity + familiarity:fam_rate + Lq_vs_NA:fam_rate:familiarity) %>% 
  tidy() %>% 
  filter(str_detect(term, "Lq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Positive Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")
```

## Combined negative measures (... same as above)
```{r}
lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + CRN_vs_NA) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Negative Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Hq_vs_Lq) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Negative Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Pol_vs_NonPol) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Negative Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + CRN_vs_NA:fam_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Negative Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + CRN_vs_NA_pol:fam_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Negative Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + Hq_vs_Lq:fam_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Negative Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate +  fam_rate:Pol_vs_NonPol) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Negative Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + familiarity + familiarity:fam_rate + Hq_vs_Lq:fam_rate:familiarity) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Negative Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma~ (1|ID) + (1|Publisher) + (1|Article) + fam_rate + familiarity + familiarity:fam_rate + CRN_vs_NA_pol:fam_rate:familiarity) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect for output measure: Negative Qs") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")
```

## Political Rates
```{r}
lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_rate + CRN_vs_NA:pol_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_rate + CRN_vs_NA_pol:pol_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_rate + Hq_vs_Lq:pol_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_rate +  pol_rate:Pol_vs_NonPol) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_rate + CRN_vs_NA:pol_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_rate + CRN_vs_NA_pol:pol_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_rate + Hq_vs_Lq:pol_rate) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate_negative/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_rate +  pol_rate:Pol_vs_NonPol) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

```

## Publisher Effects
```{r}
lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Hq_vs_Lq:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + familiarity + familiarity:Publisher + familiarity:Hq_vs_Lq:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Hq_vs_NA:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + familiarity + familiarity:Publisher + familiarity:Hq_vs_NA:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Lq_vs_NA:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "Lq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + familiarity + familiarity:Publisher + familiarity:Lq_vs_NA:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "Lq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + CRN_vs_NA:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + familiarity + familiarity:Publisher + familiarity:CRN_vs_NA:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + CRN_vs_NA_pol:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + familiarity + familiarity:Publisher + familiarity:CRN_vs_NA_pol:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + Pol_vs_NonPol:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + familiarity + familiarity:Publisher + familiarity:Pol_vs_NonPol:Publisher) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")
```

## Individual Effects (Political Leaning)
```{r}
lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_leaning + Hq_vs_Lq:pol_leaning) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_leaning + Lq_vs_NA:pol_leaning) %>% 
  tidy() %>% 
  filter(str_detect(term, "Lq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_leaning + Pol_vs_NonPol:pol_leaning) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")
```

# Individual Effects (Need For Cognition)
```{r}
output_estimate$new_nfcscore <- as.character(output_estimate$nfc_score)

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + new_nfcscore + CRN_vs_NA:new_nfcscore) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + new_nfcscore + Hq_vs_Lq:new_nfcscore) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + new_nfcscore + Lq_vs_NA:new_nfcscore) %>% 
  tidy() %>% 
  filter(str_detect(term, "Lq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + new_nfcscore + Pol_vs_NonPol:new_nfcscore) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")
```

# Individual Effects (Age)
```{r}
lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + bin_age + CRN_vs_NA:bin_age) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + bin_age + Hq_vs_Lq:bin_age) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + bin_age + Hq_vs_NA:bin_age) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + bin_age + Lq_vs_NA:bin_age) %>% 
  tidy() %>% 
  filter(str_detect(term, "Lq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + bin_age + Pol_vs_NonPol:bin_age) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")
```

# Individual Effects (Education)
```{r}
lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + education_level + CRN_vs_NA:education_level) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + education_level + Hq_vs_Lq:education_level) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + education_level + Hq_vs_NA:education_level) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + education_level + Lq_vs_NA:education_level) %>% 
  tidy() %>% 
  filter(str_detect(term, "Lq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + education_level + Pol_vs_NonPol:education_level) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")
```

# Individual Effects (Political Interest)
```{r}
lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_interest + CRN_vs_NA:pol_interest) %>% 
  tidy() %>% 
  filter(str_detect(term, "CRN")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_interest + Hq_vs_Lq:pol_interest) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_interest + Hq_vs_NA:pol_interest) %>% 
  tidy() %>% 
  filter(str_detect(term, "Hq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_interest + Lq_vs_NA:pol_interest) %>% 
  tidy() %>% 
  filter(str_detect(term, "Lq")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")

lmer(data = output_estimate,
     formula = mean_estimate/avg_sigma ~ (1|ID) + (1|Publisher) + (1|Article) + pol_interest + Pol_vs_NonPol:pol_interest) %>% 
  tidy() %>% 
  filter(str_detect(term, "Pol")) %>%
  dwplot(dodge_size = 0.6) + xlab("Average Treatment Effect") +     
  geom_vline(xintercept = 0, color = "black", alpha = 0.5, linetype = "longdash")
```